"""add analysis json

Revision ID: c11cb72da41a
Revises: 7e2403d5f4f5
Create Date: 2026-07-02 02:33:38.430977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11cb72da41a'
down_revision: Union[str, Sequence[str], None] = '7e2403d5f4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('analysis_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'analysis_json')
    # ### end Alembic commands ###
